apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::417132395153:role/eksctl-my-cluster-addon-iamserviceaccount-kub-Role1-G2brbf0yLm4T
