
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name}}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    name: {{ .Values.metadata.labels.app }}
    app: {{ .Values.metadata.labels.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.metadata.labels.app }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - name: bookweb-port
          containerPort: {{ .Values.service.port }}
