apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-web-ingress
  namespace: book-app 
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    # alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ingressClassName: alb
  rules:
    - host: app.lazaai.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: book-web-service
                port:
                  number: 80