
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name}}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    name: {{ .Values.metadata.labels.name }}
    app: {{ .Values.metadata.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  template:
    metadata:
      labels: 
        app: {{ .Values.metadata.labels.app }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - name: bookapp-port
          containerPort: {{ .Values.service.port }}
        env:
        - name: MONGO_URI
          valueFrom:
             secretKeyRef:
                name: mongo-atlas-conn
                key: MONGO_URI
        readinessProbe:
           httpGet:
             path: /health
             port: {{ .Values.service.port }}
           initialDelaySeconds: 5
           periodSeconds: 10
           failureThreshold: 3

