apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{ .Values.service.labels | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: bookapp-port
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.metadata.labels.app }}

